version: '3.7'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./../:/var/www/html/
    image: soap-test
    container_name: soap-test-php
    restart: unless-stopped